### ISSUE TITLE
Release 4.3.0 proposal

### ISSUE THREAD

**Issue by nerro** [nerro/table-layout#18]
* Issues:
  - [x] #16 - Java Compatibility lower to 1.5
  - [x] #17 - Fix Travis-CI configuration
  - [x] #20 - Error when building javadocs
* Deployment:
  - [x] deploy to Sonatype Staging repository
  - [x] deploy to Sonatype Release repository
  - [x] drop Sonatype Staging repository
* Documentation:
  - [x] prepare release notes
  - [x] build javadoc
  - [x] update `gh-pages` branch
